import type { ReactElement } from 'react' 
import type { IPreview } from '../types/types'

import Head from 'next/head'
import Layout from '../components/layout'
import Item from '../components/Item'
// import Image from 'next/image'

import * as mockup_FEAT from '../public/featured.json'
import styles from '../styles/Home.module.scss'

function Home(props: {featured: {default: IPreview[]}}) {
  return (
  <div className={styles.container}>
    <Head>
      <title>Furniture</title>
      <meta name='description' content='Generated by create next app' />
      <link rel='icon' href='/favicon.ico' />
    </Head>

    <main className={styles.main}>
      <div className={styles.intro}>
	<div className={styles.text}>
	  <h1 className={styles.title}>
	    This is a test
	  </h1>

	  <p className={styles.description}>
	    A placeholder description
	  </p>
	</div>
      </div>

      <div className={styles.featured}>
	<h1 className={styles.title}> 
	  Curated Items
	</h1>

	<div className={styles.flexrow}>
	  {props.featured.default.map((el: IPreview) => (
	    <Item key={el.id}
	      id={el.id} name={el.name}
	      img={el.img} price={el.price}
	      rating={el.rating}
	    />
	  ))}

	</div>
      </div>
      
      <div className={styles.categories}>
	<h1 className={styles.title}>
	  Browse by Categories
	</h1>
	<div className={styles.doublegrid}>
      
	</div>
      </div>
    </main>
  </div>
  )
}

Home.getLayout = function getLayout(page: ReactElement) {
  return (
    <Layout>{page}</Layout>
  )
}

export async function getStaticProps(){
  // had to do it this way to replicate grabbing data from an api
  const featured = await JSON.parse(JSON.stringify(mockup_FEAT))
  return {
    props: { featured }
  }
}

export default Home
