import type { NextPageWithLayout } from './_app'
import type { ReactElement } from 'react' 

import Head from 'next/head'
import Layout from '../components/layout'
// import Image from 'next/image'

import styles from '../styles/Home.module.scss'

const Home: NextPageWithLayout = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
	<div className={styles.intro}>
	  <div className={styles.text}>
	    <h1 className={styles.title}>
	      This is a test
	    </h1>

	    <p className={styles.description}>
	      A placeholder description
	    </p>
	  </div>
	</div>
      </main>

    </div>
  )
}

Home.getLayout = function getLayout(page: ReactElement) {
  return (
    <Layout>{page}</Layout>
  )
}

export default Home
